language: java
jdk:
- oraclejdk7
- openjdk6
- oraclejdk8
branches:
  except:
  - www
cache:
  apt: true
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- sudo apt-get -q update
- sudo apt-get -q install --no-install-recommends pandoc
- pip install --user pandocfilters
- git fetch --depth=10000 origin
install: ./gradlew ciPrep
script: ./gradlew ciBuild
after_success:
- ./gradlew ciPublish
env:
  global:
  - TERM=dumb
  # CI_DEPLOY_USER
  - secure: D3tCdALkjsp9W1hs1A32FaIOB0VkGT6+dG8maFY+In7wAF2KQ/jkYkYG+uutPn01gjaZgQiaGzal+Ck97+kfHMnm4YrK41mCL6XbZy3O7x68e/VK0GUVOJf88L8/bH2OhS33KA9Bif73I1eBy4ZfuQhXeh/UXqh7zOyOnYV1sJQ=
  # CI_DEPLOY_PASSwORD
  - secure: IhWXB3LGdaEoiD7lgdaH83aVw/yK4T/f2lNalQn8skdA4nsLA1IWNgXU9MOFPTg50699oNiZOd39SptX5guZ25K0ov4nYXxPm1qCS6YpganfzeSiZ3sRZgBXKeTOnfzh8damVsDvebHYRMdPnjb1mELaoasNCHSfzprXL+PZois=
  - SITE_UPLOAD_URL=http://dev.grouplens.org/cgi/lenskit/site_upload.py
  # UPLOAD_SECRET
  - secure: O3DZVMifyBuguxnoLHG9YiWyJd6tOjAXdT8Mve27iw3fT1T3yZ2Jfx/9RPYlvEfOYVXbpeEkR/aDb1d+4RiipF/77/1RIRl1Rh9c+sjsJPosc1zwJImHzeUBMFBBYzfI3X58qB7q0oRanUcA5bIBi9B7t+krybQZUWp9QEgnTIw=
