language: java
jdk:
- oraclejdk7
- oraclejdk8
addons:
  apt:
    packages:
      - python-pandas
branches:
  except:
  - www
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- git fetch --depth=10000 origin
install: ./gradlew ciPrep --stacktrace
script: ./gradlew ciTest --stacktrace --parallel
env:
  global:
  - TERM=dumb
  - TZ=CST6CDT
sudo: false
